#!/usr/bin/env node

const {
	init, addCommands, close
} = require('./helpers/commander');

const { setVar } = require('./helpers/variables');

const start = async () => {
	// setting base paths
	setVar('cliPath', __dirname);
	setVar('projectPath', process.cwd());

	// initialise the commander
	await init();

	// register commands to the commander
	await addCommands();

	// close commander
	await close();
};

start();

// var exec = require('child_process').exec;

// if (process.argv[2]) {
//     switch (process.argv[2]) {
//         case "version":
//             exec("node commands/version");
//             process.exit(0);
//         default:
//             console.log("\x1b[33mError:\x1b[31m", "Command d", "\n\x1b[0m");
//     }
//     process.exit(0);
// }

// require("fs").readdirSync("./commands").forEach(function(file) {
//     const { command } = require("./commands/" + file);
//     console.log(command)
// });
